services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    env_file: ".env"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${PROD_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 10
    networks:
      - net
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USERNAME: ${PROD_DB_USERNAME}
        DB_PASSWORD: ${PROD_DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_ADDRESS: db
    networks:
      - net
    ports:
      - "8080:8080"

networks:
  net:
    driver: bridge

volumes:
  db_data: